### ISSUE TITLE
Aqui está dando o seguinte erro:

### ISSUE THREAD

**Issue by leoguimaraes49** [arthurtavaresdev/command-bot-twitch#1]
![image](https://user-images.githubusercontent.com/72119698/103158631-6af86280-479e-11eb-9a66-c82ba67f53e6.png)

**Comment by leoguimaraes49** [comment]
Sabe como faço para corrigir este erro?

**Comment by arthurtavaresdev** [comment]
Opa, amigo. Isto deve-se que ter algum erro de configuração no .env
Como descrito no README.MD, é necessário criar no diretório raiz.

O Principal chave, que deve estar contida no seu .env é a TWITCH_TOKEN que pode ser obtida em https://twitchapps.com/tmi/, cole conforme foi respondida pelo site, sem quaisquer espaços.

Aguardo retorno.

**Comment by leoguimaraes49** [comment]
![image](https://user-images.githubusercontent.com/72119698/103162737-da884500-47d2-11eb-80cb-c2327e4529f1.png)
Criei um arquivo que se chama .env e preenchi conforme você falou, só que agora está dando esse erro:

**Comment by leoguimaraes49** [comment]
Ele envia uma mensagem nos chats mas após isso não envia mais e fica nesse erro ai

**Comment by arthurtavaresdev** [comment]
Ah sim, isto é apenas um erro de resposta visual, que estou corrigindo, mas o bot já está em funcionamento. O Tempo é regulado, no arquivo args.json, no argumento "interval", é esse tempo é dado em minutos. Originalmente o tempo é de mandar mensagem a cada uma hora (60min).
